apiVersion: v1
kind: Pod
metadata:
        name: hello-world
spec:
        containers:
                - name: hello-world-container
                  image: registry.nicesj.com/hello-world:0.1
        imagePullSecrets:
                - name: regcred
